//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMPMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Modules : global::System.Configuration.ApplicationSettingsBase {
        
        private static Modules defaultInstance = ((Modules)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Modules())));
        
        public static Modules Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LoadAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LoadAssemblies"]));
            }
            set {
                this["LoadAssemblies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CDKeyValidatorXMP")]
        public string ICDKeyValidator {
            get {
                return ((string)(this["ICDKeyValidator"]));
            }
            set {
                this["ICDKeyValidator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LogWriterFile")]
        public string ILogWriter {
            get {
                return ((string)(this["ILogWriter"]));
            }
            set {
                this["ILogWriter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GameStatsLogFile")]
        public string IGameStatsLog {
            get {
                return ((string)(this["IGameStatsLog"]));
            }
            set {
                this["IGameStatsLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebLogWriterFile")]
        public string IWebLogWriter {
            get {
                return ((string)(this["IWebLogWriter"]));
            }
            set {
                this["IWebLogWriter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionLogWriterFile")]
        public string IConnectionLogWriter {
            get {
                return ((string)(this["IConnectionLogWriter"]));
            }
            set {
                this["IConnectionLogWriter"] = value;
            }
        }
    }
}
