//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMPMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeRequired {
            get {
                return ((bool)(this["SettingsUpgradeRequired"]));
            }
            set {
                this["SettingsUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.UInt16> ListenPorts {
            get {
                return ((global::System.Collections.Generic.List<System.UInt16>)(this["ListenPorts"]));
            }
            set {
                this["ListenPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public ushort WebServerListenPort {
            get {
                return ((ushort)(this["WebServerListenPort"]));
            }
            set {
                this["WebServerListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>+</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection WebServerListenAddresses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WebServerListenAddresses"]));
            }
            set {
                this["WebServerListenAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U2XMP Web-Based Master Server List")]
        public string WebServerServerHeader {
            get {
                return ((string)(this["WebServerServerHeader"]));
            }
            set {
                this["WebServerServerHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u2xmp")]
        public string WebServerSkinFolder {
            get {
                return ((string)(this["WebServerSkinFolder"]));
            }
            set {
                this["WebServerSkinFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string WebServerGameTypeFilter {
            get {
                return ((string)(this["WebServerGameTypeFilter"]));
            }
            set {
                this["WebServerGameTypeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maps/")]
        public string WebServerMapUrl {
            get {
                return ((string)(this["WebServerMapUrl"]));
            }
            set {
                this["WebServerMapUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logs\\web")]
        public string WebServerLogFolder {
            get {
                return ((string)(this["WebServerLogFolder"]));
            }
            set {
                this["WebServerLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wwwroot")]
        public string WebRootFolder {
            get {
                return ((string)(this["WebRootFolder"]));
            }
            set {
                this["WebRootFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logs")]
        public string LogFolder {
            get {
                return ((string)(this["LogFolder"]));
            }
            set {
                this["LogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logs\\net")]
        public string ConnectionLogFolder {
            get {
                return ((string)(this["ConnectionLogFolder"]));
            }
            set {
                this["ConnectionLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stats")]
        public string StatsFolder {
            get {
                return ((string)(this["StatsFolder"]));
            }
            set {
                this["StatsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalIgnoreGameTypeFilter {
            get {
                return ((bool)(this["GlobalIgnoreGameTypeFilter"]));
            }
            set {
                this["GlobalIgnoreGameTypeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MatchID {
            get {
                return ((int)(this["MatchID"]));
            }
            set {
                this["MatchID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MSListEnabled {
            get {
                return ((bool)(this["MSListEnabled"]));
            }
            set {
                this["MSListEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MSListMaxServers {
            get {
                return ((int)(this["MSListMaxServers"]));
            }
            set {
                this["MSListMaxServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public string[] MSListServers {
            get {
                return ((string[])(this["MSListServers"]));
            }
            set {
                this["MSListServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfUnsignedShort xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <unsignedShort>27900</unsignedShort>
  <unsignedShort>27900</unsignedShort>
  <unsignedShort>27900</unsignedShort>
  <unsignedShort>27900</unsignedShort>
</ArrayOfUnsignedShort>")]
        public ushort[] MSListPorts {
            get {
                return ((ushort[])(this["MSListPorts"]));
            }
            set {
                this["MSListPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.UInt16> MSListInterfaces {
            get {
                return ((global::System.Collections.Generic.List<System.UInt16>)(this["MSListInterfaces"]));
            }
            set {
                this["MSListInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10023")]
        public int TelnetPort {
            get {
                return ((int)(this["TelnetPort"]));
            }
            set {
                this["TelnetPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string TelnetPassword {
            get {
                return ((string)(this["TelnetPassword"]));
            }
            set {
                this["TelnetPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rpc")]
        public string SyncServiceEndpoint {
            get {
                return ((string)(this["SyncServiceEndpoint"]));
            }
            set {
                this["SyncServiceEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("link")]
        public string SyncServiceName {
            get {
                return ((string)(this["SyncServiceName"]));
            }
            set {
                this["SyncServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection SyncServiceUris {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SyncServiceUris"]));
            }
            set {
                this["SyncServiceUris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string SyncServiceUsername {
            get {
                return ((string)(this["SyncServiceUsername"]));
            }
            set {
                this["SyncServiceUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string SyncServicePassword {
            get {
                return ((string)(this["SyncServicePassword"]));
            }
            set {
                this["SyncServicePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoIP.csv")]
        public string GeoIPDataFile {
            get {
                return ((string)(this["GeoIPDataFile"]));
            }
            set {
                this["GeoIPDataFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD5.csv")]
        public string MD5DataFile {
            get {
                return ((string)(this["MD5DataFile"]));
            }
            set {
                this["MD5DataFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BanList.txt")]
        public string BanListFile {
            get {
                return ((string)(this["BanListFile"]));
            }
            set {
                this["BanListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CDKeys.txt")]
        public string CDKeyFile {
            get {
                return ((string)(this["CDKeyFile"]));
            }
            set {
                this["CDKeyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ut2003master1.epicgames.com")]
        public string PassthroughValidatorHost {
            get {
                return ((string)(this["PassthroughValidatorHost"]));
            }
            set {
                this["PassthroughValidatorHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28902")]
        public int PassthroughValidatorPort {
            get {
                return ((int)(this["PassthroughValidatorPort"]));
            }
            set {
                this["PassthroughValidatorPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ConsoleWidth {
            get {
                return ((int)(this["ConsoleWidth"]));
            }
            set {
                this["ConsoleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int ConsoleHeight {
            get {
                return ((int)(this["ConsoleHeight"]));
            }
            set {
                this["ConsoleHeight"] = value;
            }
        }
    }
}
